--DROP TABLE DEPARTMENTS;

CREATE TABLE DEPARTMENTS 
(	
	DEPARTMENT_ID INTEGER NOT NULL, 
	DEPARTMENT_NAME VARCHAR(30), 
	MANAGER_ID INTEGER, 
	LOCATION_ID INTEGER
);

ALTER TABLE DEPARTMENTS ADD CONSTRAINT PK_DEPARTMENTS_ID PRIMARY KEY (DEPARTMENT_ID)

--DROP TABLE EMPLOYEES;

CREATE TABLE EMPLOYEES 
(	
	EMPLOYEE_ID INTEGER NOT NULL, 
	FIRST_NAME VARCHAR(20), 
	LAST_NAME VARCHAR(25), 
	EMAIL VARCHAR(25), 
	PHONE_NUMBER VARCHAR(20), 
	HIRE_DATE DATE, 
	JOB_ID VARCHAR(10), 
	SALARY FLOAT, 
	COMMISSION_PCT FLOAT, 
	MANAGER_ID INTEGER, 
	DEPARTMENT_ID INTEGER
)

ALTER TABLE EMPLOYEES ADD CONSTRAINT PK_EMPLOYEES_ID PRIMARY KEY (EMPLOYEE_ID)
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMP_DEPT_ID FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) 

--DROP TABLE LOCATIONS
CREATE TABLE LOCATIONS 
(	
	LOCATION_ID INTEGER NOT NULL, 
	STREET_ADDRESS VARCHAR(40), 
	POSTAL_CODE VARCHAR(12), 
	CITY VARCHAR(30), 
	STATE_PROVINCE VARCHAR(25), 
	COUNTRY_ID CHAR(2)
)
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATIONS_ID PRIMARY KEY (LOCATION_ID)
ALTER TABLE DEPARTMENTS ADD CONSTRAINT FK_DEPT_LOC_ID FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID) 

